### ISSUE TITLE
Nelson lbs list doesn't update routes

### ISSUE THREAD

**Issue by drewgonzales360** [getnelson/nelson#235]
If you define a route for a loadbalancer
```
loadbalancers:
- name: drewbalancer
  routes:
  - name: ingress
    expose: default->80/tcp
    destination: avtrajectories->default
```

Then change it in the next PR with the following content
```
loadbalancers:
- name: drewbalancer
  routes:
  - name: ingress
    expose: default->443/tcp
    destination: avtrajectories->default
```

nelson lbs list -n namespace will still print

```
fdd8cac3d6ff  dc1         dev        drewbalancer--1-0-0--kj483m81    80 ~> drewunit->default             avtraj-dev--1-0-0--kj483m81-somedomain.dc1.company.net
```

The route doesn't get updated.
