### ISSUE TITLE
Changes to manifest to support sidecar routing 

### ISSUE THREAD

**Issue by timperrett** [getnelson/nelson#68]
As Nelson has evolved, an interesting tension emerged with the grammer of the manifest file. During early iterations, we were bullish about revisions and quickly iterated to the current state. However, as our deployments became more sophisticated and we moved away from so-called "fat-containers" into a more "pod-like" setup, the current manifest configuration with the routing became apparent. Consider the following manifest definition:

```
units:
  - name: foobar
    description: description for the foo service
    ports:
      - default->9000/http
```

Where the physical container setup was something like:

```
  +--------------------------------------------------+
  |  +--------------------------------------------+  |
  |  |      Envoy Sidecar Proxy (port 4477)       |  |
  |  +--------------------------------------------+  |
  |  +--------------------------------------------+  |
  |  |      User Application (port 9000)          |  |
  |  +--------------------------------------------+  |
  +--------------------------------------------------+
```

In this case, the user application is meant to bind to port 9000, and 4477 is exposed by Envoy, and Nelson will map that port as needed via the scheudler at runtime, thus exposing the users application. So far so good. This works, but has some downsides, particularly when it comes to estimating resource consumption for the container... suddenly profiling one application is not sufficient (see this blog post for more information: http://timperrett.com/2017/05/13/nomad-with-envoy-and-consul

However, what if we had a physical pod setup that looked like this:

```
   +--------------------------------------------------+
   |  +--------------------------------------------+  |
   |  |      Envoy Sidecar Proxy (port 4477)       |  |
   |  +--------------------------------------------+  |
   +--------------------------------------------------+
                         | |
   +--------------------------------------------------+
   |  +--------------------------------------------+  |
   |  |      User application (port 9000)       |  |
   |  +--------------------------------------------+  |
   +--------------------------------------------------+
```

Logically, this is the same setup: we still have our proxy, and we still have our application. However, given the physical runtime layout is different, we no longer know which ports we should be mapping where, as the sidecar for envoy was not specified by the user in their manifest. Typically speaking, when it comes to sidecars Nelson has favored these being provisioned and configured by administrators, such that best practices come for free for users, but with regards to routing other problems exist that make this harder to do. Consider the following use cases:

* user application exposes a single port (agreed upon convention for arguments sake), and the proxy is configured to always use that port. This should largely work with the current setup.

* user application exposes n+1 ports (e.g. application + monitoring, and specifies ports for both). How should we then configure the proxy side car? Provide some convention for port numbers or ranges? That seems like a crappy solution. We could say that applications can only have one external port, but this would then immediately not let applications expose say, a port for internal usage with mTLS, and another with one-way TLS from an externally rooted CA.

In short, we have two choices: either present the full power of the routing container port binding to the user, or we define a set of conventions for use. I'm concerned about both paths as they have drawbacks all the same. The options are something like this:

* Add a new top-level block to the manifest called `routing` (or some such) that allows the definition of routing side-car configurations, which then have to be paired together with a unit in the `plan` section. This is flexible, but certainly prone to potential miss-configuration if users do not exactly line up the ports. This would - most likely - but subject to heavy cut-and-paste in the common case (k8s has this problem with all its varios NodePort configs etc). Consider the following example:

```
units:
- name: foobar
  description: description for the foo service
  ports:
  - default->9000/http

routing:
  name: envoy
  routes:
  - expose: internal->4477/https
    destination: internal->default
  - expose: external->4488/https
    destination: external->default
```

I'm not wild about this as its basically a duplication of load balancer, with slightly different semantics but all the same content. 

* Add a `routing` block to the `units` element definition. If a routing config is specified by the administrator in `nelson.cfg`, Nelson could enforce that a routing block was specified if `ports` was non-empty. This arragement sucks when building systems that simply want to require different authentication. For example:

```
units:
- name: foobar
  description: description for the foo service
  ports:
  - default->9000/http
  routing:
  - expose: internal->4477/https
    destination: internal->default
  - expose: external->4488/https
    destination: external->default
```

In this case how would the sidecar know what ports to configure in what way? This would end up being a convention also (maybe not a huge problem), but it just feels a little opaque / superfluous.
