### ISSUE TITLE
Integrate Vault K8S auth

### ISSUE THREAD

**Issue by timperrett** [getnelson/nelson#96]
In order to K8S jobs on Nelson to leverage the K8S<->Vault integration [1] some additional functionality will be needed from Nelson. At present, Nelson generates a policy-per stack, and provides access to the needed credentials via that per-stack policy. In order to solve the secret introduction problem outside of Nomad (which inherently solves secure introduction between vault and the scheduler), Nelson will have to conduct a write to the K8S auth API andpoint [2] to allow the policy that Nelson already created, to be assumed by a given `ServiceAccount`. The author proposes that we operate a simple convention where we assume that the runtime `ServiceAccount` name matches the stack-name (which is what we've used everywhere else). 

- [x] add support for create service account in `KubernetesClient`
- [ ] add support for create cluster role binding in `KubernetesClient`
- [ ] update the vault client to support k8s auth calls
- [ ] add a new workflow that supports k8s + integrated vault JWT

[1] https://www.vaultproject.io/docs/auth/kubernetes.html
[2] https://www.vaultproject.io/api/auth/kubernetes/index.html

This would mean that blueprints wishing to leverage Vault would end up having to specify a `RoleBinding` or `ClusterRoleBinding`, as per their setup needs, which connects the given stack `Deployment` with the `ServiceAccount` convention. An example might be something like:

```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: example-1-2-3-xqdefg
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: example-1-2-3-xqdefg
  namespace: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: example-1-2-3-xqdefg
  namespace: dev
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: example-1-2-3-xqdefg
  labels:
    tbn_cluster: example-1-2-3-xqdefg
spec:
  replicas: 2
  template:
    metadata:
      labels:
        tbn_cluster: example-1-2-3-xqdefg
    spec:
      containers:
      - name: application
        image: some/image:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
            name: private
            protocol: TCP
```
